project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "5293 Final Porject"
  author:
    - Xinrong Dong (UNI1)
    - Tiantian Li (UNI2)
  repo-url: https://github.com/xr0706/Final5293_Xinrong_Tiantian
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - step1.qmd
    - step2.qmd
    - step3.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


